services:
  backend:
    restart: unless-stopped
    #    build: ./backend
    image: gama/backend-app:1.0
    ports:
      - '3000:3000'
      - '5555:5555'
    environment:
      - JWT_SECRET= "ADALAHINTINYA"
      - DATABASE_URL="postgresql://postgres:akunPostgres5@10.3.3.2:5432/inventory_pt"

  frontend:
    restart: unless-stopped
    #    build: ./frontend
    image: gama/frontend-app:1.0
    ports:
      - '4200:80'
    depends_on:
      - backend
